# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Core 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build and publish
      run: dotnet publish -c Release -p:SelfContained=false -o ./publish

    - name: Zip published output
      run: |
        cd publish
        zip -r ../antecfluxprodisplay.zip .
        cd ..

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: antecfluxprodisplay.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
