name: Build and Release Flux Pro Display app

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Core 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Update appsettings.json version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Updating appsettings.json with correct version..."
        sed -i "s/\"Version\": *\"[^\"]*\"/\"Version\": \"$VERSION\"/" appsettings.json
      
    - name: Build and publish
      run: dotnet publish -c Release -r win-x64 -p:SelfContained=false -o ./publish

    - name: Zip published output
      run: |
        cd publish
        zip -r ../antecfluxprodisplay.zip .
        cd ..

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: antecfluxprodisplay.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
